### ISSUE TITLE
Error in library(amplicon) : there is no package called ‘amplicon’

### ISSUE THREAD

**Issue by B-1991-ing** [YongxinLiu/EasyMicrobiome#1]
Dear EasyMicrobiome development team,

I already downloaded the source code of EasyMicrobiome v1.16 (2022.8). I want to visualise the kraken+bracken output using the script **EasyMicrobiome/script/tax_stackplot.R**. But, I am not sure no output generated.

**Command lines**
module load tools computerome_utils/2.0
module load gcc/7.4.0
module load intel/perflibs
module load R/4.2.0
module load ampliconsuite-pipeline/20221021
chmod +x /PATH/EasyMicrobiome/linux/*
export PATH=$PATH:`pwd`/PATH/EasyMicrobiome/linux:`pwd`/PATH/EasyMicrobiome/script"

/services/tools/R/4.2.0/bin/Rscript /PATH/EasyMicrobiome/script/tax_stackplot.R \
    --input /bracken/bracken_1_24/bracken_1/1_P_nt.bracken  \
    --output //bracken/bracken_1_24/bracken_1/1_P_nt.bracken.stackplot \
    --legend 10 --width 89 --height 59

**Error screenshot**
<img width="1003" alt="Screenshot 2023-01-27 at 14 11 28" src="https://user-images.githubusercontent.com/54441633/215095001-5e03f48f-b135-4a31-9338-284eceacde07.png">

Could you give me some suggestions?

Best,

Bing

**Comment by YongxinLiu** [comment]
https://github.com/microbiota/amplicon
